### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by AntonioDannemann**
Created home page with camera button, still blank just for position purpose, camera button is working with the js controller.

### CODE REVIEW

**Comment by wJoenn** [comment]
Can we have a screenshot ?

**Comment by AntonioDannemann** [comment]
sorry I forgot

**Comment by AntonioDannemann** [comment]
https://user-images.githubusercontent.com/112712290/222898405-236dd46e-5c23-4b3a-a690-b52ffbae76d0.mov

as I said it is just blank with the camera button

**Comment by AntonioDannemann** [comment]
but the button is working to open the camera

**Comment by wJoenn** [comment]
Ok, the thing is this PR is supposed to have a home page that is not blank and a camera button that doesn't work yet.
You're doing things in the wrong order Antonio.

Plus the camera thing will be a form with rails, I'm pretty sure it will have nothing to do with JS in the end product though I might be wrong

**Review by wJoenn — CHANGES_REQUESTED** [review]
Ok, the thing is this PR is supposed to have a home page that is not blank and a camera button that doesn't work yet.
You're doing things in the wrong order Antonio.

Plus the camera thing will be a form with rails, I'm pretty sure it will have nothing to do with JS in the end product though I might be wrong

**Comment by wJoenn** [comment]
If I trust this SO post then it's just a matter of adding `accept="capture=camera"` to our file input

**Comment by AntonioDannemann** [comment]
Ok sorry, i will continue on the homepageCom meus cumprimentos,Antonio DannemannOn 4 Mar 2023, at 11:51, Louis Ramos ***@***.***> wrote:﻿
@wJoenn requested changes on this pull request.

Ok, the thing is this PR is supposed to have a home page that is not blank and a camera button that doesn't work yet.
You're doing things in the wrong order Antonio.
Plus the camera thing will be a form with rails, I'm pretty sure it will have nothing to do with JS in the end product though I might be wrong

**Comment by AntonioDannemann** [comment]
here is the last image for our homepage: 
Screenshot 2023-03-05 at 16 51 19

**Comment by AntonioDannemann** [comment]
Screenshot 2023-03-06 at 17 35 09

**Comment by AntonioDannemann** [comment]
the intention  that this image will scroll on the x-axis here is the full image
download

**Comment by wJoenn** [comment]
Still need to be worked on. Atm the homepage is just a background image and a title.
Try working on the rest of the page and to make this page's html seemingly complete

**Comment by AntonioDannemann** [comment]
Hey, I’m not entirely sure what do you mean, basically the home page is like this, there are other elements that are coming other PRs no? Like the navbar and the dragable cards

**Comment by wJoenn** [comment]
The homepage should look completed.
If there are some features that we'll add later, and there will be you're right, you still need to prepare the groudwork.
We're gonna add a map ? Well make the div that is gonna contain that map and give it a placeholder image
We're gonna add a random monument everyday ? Well the layout should be ready for that.
All of the features will have subtitles right ? A paragraph too maybe. You need to add that.

Look at what Mariana did for the rentart for example
The banner was ready with all the necessary buttons and css, even though the buttons redirected to the same page they were still there.
A space for the registration form was there with a title and a placeholder image
A space for the category display was there too.

Atm you have a background-image, not a homepage.
Is the logo gonna be just a title for example ? No branding ? No custom logo ? Even for rentart you have a artify logo that you added to the navbar.
And the button for the camera, you're 100% satisfied with the look of it ? In your opinion this is a button that'll stay until the end of the project ?

Take a look at this website for example
https://bloomphotographyca.com/

Sure there's a footer and a navbar but there's more in between beside the fullscreen image right ?

**Comment by AntonioDannemann** [comment]
ok, I will get to it today!

**Comment by AntonioDannemann** [comment]
https://user-images.githubusercontent.com/112712290/224145867-e0ad32e5-5630-4840-8018-0dec6c17b842.mov

**Review by wJoenn — APPROVED** [review]

**Pull request merged**
