### PR TITLE
Created a basic search form component

### PR DESCRIPTION
**Pull request by wJoenn**
Part of https://github.com/wJoenn/artify/issues/59

The results are hardcoded at the moment but once this is merged I'll work on making it reactive with Ajax to display results as the user type in the form

image

### CODE REVIEW

**Comment by wJoenn** [comment]
image

**Comment by Glod33** [comment]
I would try to integrate the search bar inside the navbar below, in an animation. That gives a bit more space.

Also perhaps the city is not necessary as you can add a second search option that should be able to handle that automatically. I think that would be more user friendly.

**Comment by wJoenn** [comment]
To be honest I'm not sure the navbar will stay.

The idea at the moment is that the homepage would start with the navbar at the top with an empty div under it and if you type something the div is populated as you type to show the results so it wouldn't make sense to type in the navbar but the content appear in the page, potentially not appearing on the screen.
As for the search options I know that with PG search we can search through multiple attributes at once but I felt that, contrary to what you're saying, it would be more user friendly to have a button that clearly indicates that you can search by City too.
I feel like an older person, 60+ for example, wouldn't really think of searching by keyword instead of something  specific 🤔 

In any case this is just a test I'm doing but I'm very far from completing the homepage and I'd like to submit a completed idea before we evaluate the design of it if you don't mind. If the code exist we can always move it somewhere else if we want to anyway, like move the search bar inside the navbar later on for example

**Comment by wJoenn** [comment]
The filters also serve as a way to add some color to the component and enhance the design.
I'm trying stuffs 😅

**Review by Glod33 — APPROVED** [review]

**Pull request merged**
