### PR TITLE
Photo bug fix

### PR DESCRIPTION
**Pull request by wJoenn**
The only fix I could think of in case Wikipedia's API doesn't find a main image is to remove the validation for the photo and to have a class method on the Monument model that returns every instances that don't have a photo.
We can then use he #attach_photo instance method to upload a file manually by checking the Monument.without_photo array from time to time.

- It's either that or pick a random image from wikipedia in hope that it's a relevant one which imo is a bad idea
- Or use another API to get an image, probably google search or something like that, and pick the first image in hope it's a relevant one.  It's a compromise I would be willing to take but I ahven't really looked into it.

I also fixed a bug where the camera form would submit even if the user cancel the file file selection. It now submit only once a file has been chosen.

### CODE REVIEW

**Comment by Glod33** [comment]
Can't we have a standard image(with text an illustration) as a replacement?

**Comment by wJoenn** [comment]
I don't understand, can you show me an example ?

**Comment by Glod33** [comment]
A placeholder with a text like:
"We don't have a picture for that"
"Sorry"
I have an idea for a design, but I'll get to that later.

**Comment by wJoenn** [comment]
Oh right, well sure we'll do that but that's gonna be part of the show page css, not an actual file attached to the model.
The show page hasn't been done yet

**Pull request merged**
